# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  ...
}:

{
  imports = [ ];

  hardware.enableRedistributableFirmware = true;

  boot.hardwareScan = true;
  boot.kernelPackages = pkgs.linuxPackages_zen;
  boot.initrd.availableKernelModules = [
    "nvme"
    "ahci"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [
    "dm-snapshot"
    "amdgpu"
  ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ ];

  services.lvm.boot.thin.enable = true;

  fileSystems."/" = {
    device = "/dev/mapper/root";
    fsType = "ext4";
    options = [
      "discard"
      "noatime"
    ];
  };

  boot.initrd.luks.devices."root" = {
    device = "/dev/disk/by-label/nixos";
    allowDiscards = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E14E-10D7";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
      "noatime"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-label/swap"; }
  ];

  environment.etc.crypttab = {
    mode = "0600";
    text = ''
      # <volume-name> <encrypted-device> [key-file] [options]
      microvm-alice	UUID=9d2ee436-b47b-4023-942d-3a3f1c2a5227	none	noauto,discard,fido2-device=auto
      microvm-oscar	UUID=8fc08548-c359-479f-abce-0bf5e36d9959	none	noauto,discard,fido2-device=auto
    '';
  };

  services.udev.extraRules = ''
    SUBSYSTEM=="usb", ATTR{idVendor}=="18d1", ATTR{idProduct}=="9470", GROUP="kvm"
    SUBSYSTEM=="usb", ATTR{idVendor}=="04e8", ATTR{idProduct}=="61fb", GROUP="kvm"

    # CHECK: # udevadm info /dev/mapper/xxx
    # KERNEL Device Name, Block Device, DM_NAME, Action
    KERNEL=="dm-*", SUBSYSTEM=="block", ENV{DM_NAME}="microvm-*", ACTION=="add", GROUP="kvm", MODE="0660"
  '';

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp39s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp49s0f3u1u1u4.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp41s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # AMD_GPU https://nixos.wiki/wiki/AMD_GPU
  hardware = {
    graphics = {
      enable = true;
      enable32Bit = true;
    };
    uinput.enable = true;
  };

  services.lact.enable = true;
}
